version: '3.0'

expectations:
  population_size: 1000000

actions:
  
  # generate metadata
  design:
    run: r:latest analysis/design.R
    outputs:
      moderately_sensitive:
        lib: analysis/lib/*

  # extract study population
  generate_study_population:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition
    needs: 
    - design
    outputs:
      highly_sensitive:
        cohort: output/extract/input.feather

  # generate custom dummy data
  generate_dummy_data:
    run: r:latest analysis/dummy_data.R
    needs:
    - design
    - generate_study_population
    outputs:
      highly_sensitive:
        dummydata: output/extract/dummy_data.feather
        
  process_extract:
    run: r:latest analysis/process_extract.R
    needs:
    - generate_study_population
    - generate_dummy_data
    outputs:
      highly_sensitive:
        data: output/extract/data_eligible.rds
      moderately_sensitive:
        skim: output/extract/skim_*.txt
        flowchart: output/extract/flowchart_*.csv
        
  exploratory_analysis:
    run: r:latest analysis/exploratory_analysis.R
    needs: 
    - process_extract
    outputs:
      moderately_sensitive:
        data_vax_counts: output/exploratory/data_vax_counts_midpoint6.csv
        group_counts: output/exploratory/combined_data_bar_plot_midpoint6.csv
        vax_dates: output/exploratory/vax_dates_*.png
        strat_dist: output/exploratory/strat_dist_*.png

  kaplan_meier:
    run: r:latest analysis/kaplan_meier.R
    needs: 
    - process_extract
    outputs:
      moderately_sensitive:
        vaccine_coverage_all: output/kaplan_meier/vaccine_coverage_all_midpoint6.csv
        km_plot_*: output/kaplan_meier/km_plot_*.png
